nvbach91/4IZ278-2024-2025-LS

www/valp07/cv01/css/styles.css, www/valp07/cv01/img/logo.svg, www/valp07/cv01/index.php
Odevzdávám cvičení 01
odkaz na práci na serveru eso je https://eso.vse.cz/~valp07/cv01/
=> valp07-cv01

www/monj06/cv01/css/styles.css, www/monj06/cv01/index.php
Odevzdávám cvičení 01 https://eso.vse.cz/~monj06/4IZ278/cv01/
=> monj06-cv01

www/mark48/cv01/index.php, www/mark48/cv01/styles/card.css
Odevzdávám úkol z cv01 - https://eso.vse.cz/~mark48/cv01/
=> mark48-cv01

www/vrat03/cv01/css/style.css, www/vrat03/cv01/index.php
Odevzdávám úkol z 1. cvičení. Odkaz na server eso: [https://eso.vse.cz/~vrat03/cv01/](https://eso.vse.cz/~vrat03/cv01/).
=> vrat03-cv01

www/tra09/cv02/Person.php, www/tra09/cv02/footer.php, www/tra09/cv02/header.php, www/tra09/cv02/index.php, www/tra09/cv02/utils.php
https://eso.vse.cz/~trah09/cv02/
=> trah09-cv02

www/fedm05/cv03/css/style.css, www/fedm05/cv03/includes/foot.php, www/fedm05/cv03/includes/head.php, www/fedm05/cv03/index.php, www/fedm05/cv03/utils/form.php
[https://eso.vse.cz/~fedm05/cv03](https://eso.vse.cz/~fedm05/cv03)
=> fedm05-cv03

www/vrat03/cv03/css/style.css, www/vrat03/cv03/includes/foot.php, www/vrat03/cv03/includes/head.php, www/vrat03/cv03/index.php
Odevzdávám úkol z 3. cvičení. 
Odkaz na server eso: [https://eso.vse.cz/~vrat03/cv03/](https://eso.vse.cz/~vrat03/cv03/).
=> vrat03-cv03

www/dlam01/cv03/classes/Player.php, www/dlam01/cv03/css/styles.css, www/dlam01/cv03/form.php, www/dlam01/cv03/includes/footer.php, www/dlam01/cv03/includes/header.php, www/dlam01/cv03/index.php, www/dlam01/cv03/profile.php
https://eso.vse.cz/~dlam01/cv03/
=> dlam01-cv03

www/lugp00/cv03/footer.html, www/lugp00/cv03/header.html, www/lugp00/cv03/index.php
Odevzdavam cviceni 03
Odkaz na praci na serveru eso je: https://eso.vse.cz/~lugp00/cv03/index.php
=> lugp00-cv03

www/zemo00/cv04/admin/users.php, www/zemo00/cv04/includes/foot.html, www/zemo00/cv04/includes/head.html, www/zemo00/cv04/index.php, www/zemo00/cv04/login.php, www/zemo00/cv04/registration.php, www/zemo00/cv04/styles/main.css, www/zemo00/cv04/utilities/user_management.php, www/zemo00/cv04/utilities/validation.php
Odevzdávám cvičení 04
https://eso.vse.cz/~zemo00/cv04/
=> zemo00-cv04

www/lugp00/cv04/admin/users.php, www/lugp00/cv04/functions.php, www/lugp00/cv04/login.php, www/lugp00/cv04/registration.php
Odevzdavam cviceni 04
Odkaz na praci na serveru eso: https://eso.vse.cz/~lugp00/cv04/login.php
=> lugp00-cv04

www/monj06/cv04/admin/users.php, www/monj06/cv04/components/form.php, www/monj06/cv04/components/login.php, www/monj06/cv04/components/registration.php, www/monj06/cv04/data/users.db, www/monj06/cv04/includes/footer.php, www/monj06/cv04/includes/header.php, www/monj06/cv04/index.php
Odevzdavam cviceni 04
https://eso.vse.cz/~monj06/4IZ278/cv04/
=> monj06-cv04

www/veji03/cv04/admin/users.php, www/veji03/cv04/includes/footer.php, www/veji03/cv04/includes/header.php, www/veji03/cv04/index.php, www/veji03/cv04/login.php, www/veji03/cv04/registration.php, www/veji03/cv04/users.db, www/veji03/cv04/utils/utils.php
Odevzdavam cvičení 4
https://eso.vse.cz/~veji03/cv04/
=> veji03-cv04

www/dlam01/cv04/admin/users.php, www/dlam01/cv04/css/adminTable.css, www/dlam01/cv04/css/styles.css, www/dlam01/cv04/fileHandling.php, www/dlam01/cv04/includes/footer.php, www/dlam01/cv04/includes/header.php, www/dlam01/cv04/index.php, www/dlam01/cv04/login.php, www/dlam01/cv04/loginForm.php, www/dlam01/cv04/profile.php, www/dlam01/cv04/registration.php, www/dlam01/cv04/registrationForm.php, www/dlam01/cv04/users.db
https://eso.vse.cz/~dlam01/cv04/
=> dlam01-cv04

www/vrat03/cv04/css/style.css, www/vrat03/cv04/includes/foot.php, www/vrat03/cv04/includes/head.php, www/vrat03/cv04/index.php, www/vrat03/cv04/login.php, www/vrat03/cv04/register.php, www/vrat03/cv04/users.php
Odevzdávám úkol z 4. cvičení. Odkaz na server eso: [https://eso.vse.cz/~vrat03/cv04/](https://eso.vse.cz/~vrat03/cv04/).
=> vrat03-cv04

www/zemo00/cv06/Database/CategoriesDB.php, www/zemo00/cv06/Database/Database.php, www/zemo00/cv06/Database/ProductsDB.php, www/zemo00/cv06/Database/database_config.php, www/zemo00/cv06/Database/database_operations.php, www/zemo00/cv06/components/CategoryDisplay.php, www/zemo00/cv06/components/ProductDisplay.php, www/zemo00/cv06/components/SlideDisplay.php, www/zemo00/cv06/includes/foot.html, www/zemo00/cv06/includes/head.html, www/zemo00/cv06/index.php, www/zemo00/cv06/styles/main.css
odevzdávám cvičení 06
https://eso.vse.cz/~zemo00/cv06/
=> zemo00-cv06

www/valp07/cv06/components/CategoryDisplay.php, www/valp07/cv06/components/ProductDisplay.php, www/valp07/cv06/components/SlideDisplay.php, www/valp07/cv06/config/global.php, www/valp07/cv06/css/styles.css, www/valp07/cv06/db/CategoriesDB.php, www/valp07/cv06/db/Database.php, www/valp07/cv06/db/DatabaseConnection.php, www/valp07/cv06/db/DatabaseOperations.php, www/valp07/cv06/db/ProductsDB.php, www/valp07/cv06/db/SlidesDB.php, www/valp07/cv06/includes/footer.php, www/valp07/cv06/includes/header.php, www/valp07/cv06/index.php
Odevzdávám cvičení 06
odkaz na práci na serveru eso je https://eso.vse.cz/~valp07/cv06/
=> valp07-cv06

www/monj06/cv06/css/styles.css, www/monj06/cv06/database/CategoriesDB.php, www/monj06/cv06/database/Database.php, www/monj06/cv06/database/DatabaseOperations.php, www/monj06/cv06/database/ProductsDB.php, www/monj06/cv06/database/SlidesDB.php, www/monj06/cv06/database/database-config.php, www/monj06/cv06/includes/categoryDisplay.php, www/monj06/cv06/includes/footer.php, www/monj06/cv06/includes/header.php, www/monj06/cv06/includes/productDisplay.php, www/monj06/cv06/includes/slideDisplay.php, www/monj06/cv06/index.php
Odevzdavam cviceni 06 https://eso.vse.cz/~monj06/4IZ278/cv06/
=> monj06-cv06

www/enga03/cv06/components/CarouselDisplay.php, www/enga03/cv06/components/CategoryDisplay.php, www/enga03/cv06/components/ProductDisplay.php, www/enga03/cv06/css/styles.css, www/enga03/cv06/database/CategoriesDB.php, www/enga03/cv06/database/Database.php, www/enga03/cv06/database/DatabaseOperation.php, www/enga03/cv06/database/ProductsDB.php, www/enga03/cv06/database/SlidesDB.php, www/enga03/cv06/includes/Footer.php, www/enga03/cv06/includes/Header.php, www/enga03/cv06/index.php
Dobrý den,
odevzdávám cvičení 06
https://eso.vse.cz/~enga03/cv06/
=> enga03-cv06

www/schd22/cv06/components/CategoryDisplay.php, www/schd22/cv06/components/ProductDisplay.php, www/schd22/cv06/components/SlideDisplay.php, www/schd22/cv06/css/style.css, www/schd22/cv06/database/CategoriesDB.php, www/schd22/cv06/database/Database.php, www/schd22/cv06/database/DatabaseConnection.php, www/schd22/cv06/database/DatabaseOperations.php, www/schd22/cv06/database/ProductDB.php, www/schd22/cv06/database/SlidesDB.php, www/schd22/cv06/database/database-config.php, www/schd22/cv06/database/database-index.php, www/schd22/cv06/incl/footer.php, www/schd22/cv06/incl/header.php, www/schd22/cv06/index.php
odevzdavam cv06
https://eso.vse.cz/~schd22/cv06/
=> schd22-cv06

www/rakf00/cv06/components/Categories.php, www/rakf00/cv06/components/Products.php, www/rakf00/cv06/components/Slider.php, www/rakf00/cv06/db/CategoryDB.php, www/rakf00/cv06/db/Database.php, www/rakf00/cv06/db/DatabaseOperations.php, www/rakf00/cv06/db/ProductDB.php, www/rakf00/cv06/db/SlidesDB.php, www/rakf00/cv06/db/UserDB.php, www/rakf00/cv06/db/db-config.php, www/rakf00/cv06/includes/foot.php, www/rakf00/cv06/includes/head.php, www/rakf00/cv06/index.php, www/rakf00/cv06/style.css
cv06 - https://eso.vse.cz/~rakf00/cv06/
=> rakf00-cv06

www/fedm05/cv06/components/CategoryDisplay.php, www/fedm05/cv06/components/ProductDisplay.php, www/fedm05/cv06/components/SlideDisplay.php, www/fedm05/cv06/css/styles.css, www/fedm05/cv06/db/CategoryDB.php, www/fedm05/cv06/db/DatabaseConnection.php, www/fedm05/cv06/db/ProductsDB.php, www/fedm05/cv06/db/SlidersDB.php, www/fedm05/cv06/index.php
[https://eso.vse.cz/~fedm05/cv06/](https://eso.vse.cz/~fedm05/cv06/)
=> fedm05-cv06

www/vrat03/cv06/css/style.css, www/vrat03/cv06/database/CategoriesDB.php, www/vrat03/cv06/database/Database.php, www/vrat03/cv06/database/DatabaseOperations.php, www/vrat03/cv06/database/ProductsDB.php, www/vrat03/cv06/database/database-config.php, www/vrat03/cv06/includes/CategoryDisplay.php, www/vrat03/cv06/includes/ProductDisplay.php, www/vrat03/cv06/includes/SlideDisplay.php, www/vrat03/cv06/includes/foot.php, www/vrat03/cv06/includes/head.php, www/vrat03/cv06/index.php, www/vrat03/cv06/products.php
Odevzdávám úkol z 6. cvičení. 
Odkaz na server eso: [https://eso.vse.cz/~vrat03/cv06/](https://eso.vse.cz/~vrat03/cv06/).
=> vrat03-cv06

www/mark48/cv06/CarouselDisplay.php, www/mark48/cv06/CategoryCard.php, www/mark48/cv06/CategoryDisplay.php, www/mark48/cv06/ProductCard.php, www/mark48/cv06/ProductDisplay.php, www/mark48/cv06/classes/Category.php, www/mark48/cv06/classes/Product.php, www/mark48/cv06/classes/Slide.php, www/mark48/cv06/db/CategoryDb.php, www/mark48/cv06/db/DbPdo.php, www/mark48/cv06/db/ProductDb.php, www/mark48/cv06/db/SlideDb.php, www/mark48/cv06/footer.php, www/mark48/cv06/head.php, www/mark48/cv06/index.php, www/mark48/cv06/styles/styles.css
Odevzdávám úkol cv06 - https://eso.vse.cz/~mark48/cv06/
=> mark48-cv06

www/zemo00/cv07/Database/Database.php, www/zemo00/cv07/Database/GoodsDB.php, www/zemo00/cv07/Database/database_config.php, www/zemo00/cv07/Database/database_operations.php, www/zemo00/cv07/buy.php, www/zemo00/cv07/cart.php, www/zemo00/cv07/components/GoodsDisplay.php, www/zemo00/cv07/create-item.php, www/zemo00/cv07/delete-item.php, www/zemo00/cv07/edit-item.php, www/zemo00/cv07/incl/foot.html, www/zemo00/cv07/incl/head.php, www/zemo00/cv07/index.php, www/zemo00/cv07/login.php, www/zemo00/cv07/logout.php, www/zemo00/cv07/remove-item.php, www/zemo00/cv07/styles/main.css
Odevzdávám cvičení 07
https://eso.vse.cz/~zemo00/cv07/
=> zemo00-cv07

www/gona11/cv06/database/database-config.php, www/gona11/cv07/add-item.php, www/gona11/cv07/buy.php, www/gona11/cv07/cart.php, www/gona11/cv07/css/style.css, www/gona11/cv07/database/Database.php, www/gona11/cv07/database/ProductsDB.php, www/gona11/cv07/database/db-config.php, www/gona11/cv07/database/db-connection.php, www/gona11/cv07/database/db-operations.php, www/gona11/cv07/delete-item.php, www/gona11/cv07/includes/foot.php, www/gona11/cv07/includes/head.php, www/gona11/cv07/index.php, www/gona11/cv07/login.php, www/gona11/cv07/logout.php, www/gona11/cv07/remove-item.php, www/gona11/cv07/requires/navbar.php, www/gona11/cv07/requires/productDisplay.php
Odevzdávám úkol č.7
https://eso.vse.cz/~gona11/cv07/
=> gona11-cv07

www/fedm05/cv07/buy-item.php, www/fedm05/cv07/cart.php, www/fedm05/cv07/components/ProductDisplay.php, www/fedm05/cv07/create-item.php, www/fedm05/cv07/css/styles.css, www/fedm05/cv07/db/DatabaseConnection.php, www/fedm05/cv07/db/ProductsDB.php, www/fedm05/cv07/incl/footer.php, www/fedm05/cv07/incl/header.php, www/fedm05/cv07/index.php, www/fedm05/cv07/login.php, www/fedm05/cv07/logout.php, www/fedm05/cv07/remove-item.php
[https://eso.vse.cz/~fedm05/cv07/](https://eso.vse.cz/~fedm05/cv07/)
=> fedm05-cv07

www/kark28/cv07/admin/users.php, www/kark28/cv07/cart.php, www/kark28/cv07/components/carouselDisplay.php, www/kark28/cv07/components/categoryDisplay.php, www/kark28/cv07/components/itemDisplay.php, www/kark28/cv07/components/loginForm.php, www/kark28/cv07/components/registrationForm.php, www/kark28/cv07/css/styles.css, www/kark28/cv07/database/CategoryDB.php, www/kark28/cv07/database/DatabaseOperations.php, www/kark28/cv07/database/ProductDB.php, www/kark28/cv07/database/UserDB.php, www/kark28/cv07/database/database-config.php, www/kark28/cv07/database/database.php, www/kark28/cv07/edit.php, www/kark28/cv07/includes/footer.php, www/kark28/cv07/includes/header.php, www/kark28/cv07/includes/navbar.php, www/kark28/cv07/index.php, www/kark28/cv07/insert.php, www/kark28/cv07/login.php, www/kark28/cv07/profile.php, www/kark28/cv07/register.php, www/kark28/cv07/utils/buy.php, www/kark28/cv07/utils/delete.php, www/kark28/cv07/utils/logout.php, www/kark28/cv07/utils/removeItem.php
[https://eso.vse.cz/~kark28/cv07/](https://eso.vse.cz/~kark28/cv07/)
=> kark28-cv07

www/valp07/cv07/buy.php, www/valp07/cv07/cart.php, www/valp07/cv07/config/global.php, www/valp07/cv07/create-item.php, www/valp07/cv07/css/styles.css, www/valp07/cv07/db/Database.php, www/valp07/cv07/db/DatabaseConnection.php, www/valp07/cv07/db/DatabaseOperations.php, www/valp07/cv07/db/ProductsDB.php, www/valp07/cv07/delete-item.php, www/valp07/cv07/edit-item.php, www/valp07/cv07/incl/footer.php, www/valp07/cv07/incl/header.php, www/valp07/cv07/index.php, www/valp07/cv07/login.php, www/valp07/cv07/logout.php, www/valp07/cv07/profile.php, www/valp07/cv07/remove-item.php
Odevzdávám cvičení 07
odkaz na práci na serveru eso je https://eso.vse.cz/~valp07/cv07/
=> valp07-cv07

www/vrat03/cv07/add-item.php, www/vrat03/cv07/buy.php, www/vrat03/cv07/cart.php, www/vrat03/cv07/css/style.css, www/vrat03/cv07/database/CategoriesDB.php, www/vrat03/cv07/database/Database.php, www/vrat03/cv07/database/DatabaseOperations.php, www/vrat03/cv07/database/ProductsDB.php, www/vrat03/cv07/database/database-config.php, www/vrat03/cv07/delete-item.php, www/vrat03/cv07/edit-item.php, www/vrat03/cv07/edit-items.php, www/vrat03/cv07/includes/CategoryDisplay.php, www/vrat03/cv07/includes/ProductDisplay.php, www/vrat03/cv07/includes/SlideDisplay.php, www/vrat03/cv07/includes/foot.php, www/vrat03/cv07/includes/head.php, www/vrat03/cv07/index.php, www/vrat03/cv07/login.php, www/vrat03/cv07/logout.php, www/vrat03/cv07/remove-item.php
Odevzdávám úkol ze 7. cvičení.
Odkaz na eso: [https://eso.vse.cz/~vrat03/cv07/](https://eso.vse.cz/~vrat03/cv07/)
=> vrat03-cv07

www/zemo00/cv10/Database/Database.php, www/zemo00/cv10/Database/GoodsDB.php, www/zemo00/cv10/Database/UsersDB.php, www/zemo00/cv10/Database/database_config.php, www/zemo00/cv10/Database/database_operations.php, www/zemo00/cv10/components/GoodsDisplay.php, www/zemo00/cv10/create-item.php, www/zemo00/cv10/delete-item.php, www/zemo00/cv10/edit-item.php, www/zemo00/cv10/home.php, www/zemo00/cv10/incl/foot.html, www/zemo00/cv10/incl/head.html, www/zemo00/cv10/index.php, www/zemo00/cv10/register.php, www/zemo00/cv10/styles/main.css, www/zemo00/cv10/user-privileges.php, www/zemo00/cv10/utilities/auth.php, www/zemo00/cv10/utilities/auth_admin.php, www/zemo00/cv10/utilities/auth_manager.php
odevzdávám cvičení 10
https://eso.vse.cz/~zemo00/cv10/
=> zemo00-cv10

www/valp07/cv10/buy.php, www/valp07/cv10/cart.php, www/valp07/cv10/config/global.php, www/valp07/cv10/create-item.php, www/valp07/cv10/css/styles.css, www/valp07/cv10/db/Database.php, www/valp07/cv10/db/DatabaseConnection.php, www/valp07/cv10/db/DatabaseOperations.php, www/valp07/cv10/db/ProductsDB.php, www/valp07/cv10/db/UsersDB.php, www/valp07/cv10/delete-item.php, www/valp07/cv10/edit-item.php, www/valp07/cv10/incl/footer.php, www/valp07/cv10/incl/header.php, www/valp07/cv10/index.php, www/valp07/cv10/login.php, www/valp07/cv10/logout.php, www/valp07/cv10/profile.php, www/valp07/cv10/registration.php, www/valp07/cv10/remove-item.php, www/valp07/cv10/user-privileges.php
Odevzdávám cvičení 10
odkaz na práci na serveru eso je https://eso.vse.cz/~valp07/cv10/
=> valp07-cv10

www/kark28/cv10/admin/users.php, www/kark28/cv10/cart.php, www/kark28/cv10/components/carouselDisplay.php, www/kark28/cv10/components/categoryDisplay.php, www/kark28/cv10/components/itemDisplay.php, www/kark28/cv10/components/loginForm.php, www/kark28/cv10/components/registrationForm.php, www/kark28/cv10/css/styles.css, www/kark28/cv10/database/CategoryDB.php, www/kark28/cv10/database/DatabaseOperations.php, www/kark28/cv10/database/ProductDB.php, www/kark28/cv10/database/UserDB.php, www/kark28/cv10/database/database-config.php, www/kark28/cv10/database/database.php, www/kark28/cv10/edit.php, www/kark28/cv10/includes/footer.php, www/kark28/cv10/includes/header.php, www/kark28/cv10/includes/navbar.php, www/kark28/cv10/index.php, www/kark28/cv10/insert.php, www/kark28/cv10/login.php, www/kark28/cv10/profile.php, www/kark28/cv10/register.php, www/kark28/cv10/utils/buy.php, www/kark28/cv10/utils/delete.php, www/kark28/cv10/utils/logout.php, www/kark28/cv10/utils/removeItem.php
[https://eso.vse.cz/~kark28/cv10/](https://eso.vse.cz/~kark28/cv10/)
=> kark28-cv10

www/mark48/cv10/ProductCard.php, www/mark48/cv10/ProductDisplay.php, www/mark48/cv10/auth.php, www/mark48/cv10/buy.php, www/mark48/cv10/cart.php, www/mark48/cv10/classes/Good.php, www/mark48/cv10/classes/User.php, www/mark48/cv10/create-item.php, www/mark48/cv10/db/DbPdo.php, www/mark48/cv10/db/GoodDb.php, www/mark48/cv10/db/UserDb.php, www/mark48/cv10/edit-item.php, www/mark48/cv10/footer.php, www/mark48/cv10/head.php, www/mark48/cv10/index.php, www/mark48/cv10/login.php, www/mark48/cv10/logout.php, www/mark48/cv10/purchase_confirm.php, www/mark48/cv10/registration.php, www/mark48/cv10/styles/styles.css, www/mark48/cv10/user-privileges.php
Odevzdávám cvičení 10 - https://eso.vse.cz/~mark48/cv10/
=> mark48-cv10

www/rakf00/cv10/Database.php, www/rakf00/cv10/adminPage.php, www/rakf00/cv10/afterLogin.php, www/rakf00/cv10/index.php, www/rakf00/cv10/login.php, www/rakf00/cv10/navbar.php, www/rakf00/cv10/php-config.php, www/rakf00/cv10/privilegeManager.php, www/rakf00/cv10/profile.php, www/rakf00/cv10/signOut.php, www/rakf00/cv10/style.css, www/rakf00/cv10/updateRemoveCreate.php
emaily: admin;manager;user    @test.com 
privilege 3;2;1
heslo pro všechny: admin
odevzdávám cv10 - https://eso.vse.cz/~rakf00/cv10/login.php
=> rakf00-cv10

www/gona11/cv07/database/db-config.php, www/gona11/cv10/add-item.php, www/gona11/cv10/buy.php, www/gona11/cv10/cart.php, www/gona11/cv10/css/style.css, www/gona11/cv10/database/Database.php, www/gona11/cv10/database/ProductsDB.php, www/gona11/cv10/database/UsersDB.php, www/gona11/cv10/database/db-config.php, www/gona11/cv10/database/db-connection.php, www/gona11/cv10/database/db-operations.php, www/gona11/cv10/delete-item.php, www/gona11/cv10/edit-item.php, www/gona11/cv10/includes/foot.php, www/gona11/cv10/includes/head.php, www/gona11/cv10/index.php, www/gona11/cv10/login.php, www/gona11/cv10/logout.php, www/gona11/cv10/register.php, www/gona11/cv10/remove-item.php, www/gona11/cv10/requires/navbar.php, www/gona11/cv10/requires/productDisplay.php, www/gona11/cv10/user-privileges.php
Odevzdávám cv.10
https://eso.vse.cz/~gona11/cv10/index.php
=> gona11-cv10

www/mark48/cv07/ProductCard.php, www/mark48/cv07/ProductDisplay.php, www/mark48/cv07/buy.php, www/mark48/cv07/cart.php, www/mark48/cv07/classes/Good.php, www/mark48/cv07/create-item.php, www/mark48/cv07/db/DbPdo.php, www/mark48/cv07/db/GoodDb.php, www/mark48/cv07/edit-item.php, www/mark48/cv07/footer.php, www/mark48/cv07/head.php, www/mark48/cv07/index.php, www/mark48/cv07/login.php, www/mark48/cv07/logout.php, www/mark48/cv07/purchase_confirm.php, www/mark48/cv07/styles/styles.css
Odevzdávám CV07 - https://eso.vse.cz/~mark48/cv07/
=> mark48-cv07

www/zemo00/cv11/Database/Database.php, www/zemo00/cv11/Database/GoodsDB.php, www/zemo00/cv11/Database/UsersDB.php, www/zemo00/cv11/Database/database_config.php, www/zemo00/cv11/Database/database_operations.php, www/zemo00/cv11/components/GoodsDisplay.php, www/zemo00/cv11/create-item.php, www/zemo00/cv11/delete-item.php, www/zemo00/cv11/edit-item.php, www/zemo00/cv11/home.php, www/zemo00/cv11/incl/foot.html, www/zemo00/cv11/incl/head.html, www/zemo00/cv11/index.php, www/zemo00/cv11/method-selection.php, www/zemo00/cv11/register.php, www/zemo00/cv11/styles/main.css, www/zemo00/cv11/user-privileges.php, www/zemo00/cv11/utilities/auth.php, www/zemo00/cv11/utilities/auth_admin.php, www/zemo00/cv11/utilities/auth_manager.php, www/zemo00/cv11/utilities/optimistic.php, www/zemo00/cv11/utilities/pessimistic.php, www/zemo00/cv11/utilities/pessimistic_lock.php
Odevzdávám cvičení 11
https://eso.vse.cz/~zemo00/cv11/
=> zemo00-cv11

www/monj06/cv11/css/styles.css, www/monj06/cv11/database/CategoriesDB.php, www/monj06/cv11/database/Database.php, www/monj06/cv11/database/DatabaseOperations.php, www/monj06/cv11/database/ProductsDB.php, www/monj06/cv11/database/SlidesDB.php, www/monj06/cv11/database/UsersDB.php, www/monj06/cv11/database/database-config.php, www/monj06/cv11/includes/buy.php, www/monj06/cv11/includes/cart.php, www/monj06/cv11/includes/categoryDisplay.php, www/monj06/cv11/includes/create-item.php, www/monj06/cv11/includes/delete-item.php, www/monj06/cv11/includes/edit-item-opt.php, www/monj06/cv11/includes/edit-item-pes.php, www/monj06/cv11/includes/footer.php, www/monj06/cv11/includes/header.php, www/monj06/cv11/includes/login.php, www/monj06/cv11/includes/logout.php, www/monj06/cv11/includes/productDisplay.php, www/monj06/cv11/includes/registration.php, www/monj06/cv11/includes/remove-item.php, www/monj06/cv11/includes/slideDisplay.php, www/monj06/cv11/includes/user-privilege.php, www/monj06/cv11/index.php
Odevzdávám cvičení 11 https://eso.vse.cz/~monj06/4IZ278/cv11/index.php
=> monj06-cv11

www/mark48/cv11/ProductCard.php, www/mark48/cv11/ProductDisplay.php, www/mark48/cv11/auth.php, www/mark48/cv11/buy.php, www/mark48/cv11/cart.php, www/mark48/cv11/classes/Good.php, www/mark48/cv11/classes/User.php, www/mark48/cv11/create-item.php, www/mark48/cv11/db/DbPdo.php, www/mark48/cv11/db/GoodDb.php, www/mark48/cv11/db/UserDb.php, www/mark48/cv11/edit-item-pessimistic.php, www/mark48/cv11/edit-item.php, www/mark48/cv11/footer copy.php, www/mark48/cv11/footer.php, www/mark48/cv11/head.php, www/mark48/cv11/index.php, www/mark48/cv11/login.php, www/mark48/cv11/logout.php, www/mark48/cv11/purchase_confirm.php, www/mark48/cv11/registration.php, www/mark48/cv11/styles/styles.css, www/mark48/cv11/user-privileges.php
Odevzdávám cvičení 11 - https://eso.vse.cz/~mark48/cv11/
=> mark48-cv11

www/vrat03/cv11/database/Database.php, www/vrat03/cv11/database/database-config.php, www/vrat03/cv11/edit_optimistic.php, www/vrat03/cv11/edit_pessimistic.php, www/vrat03/cv11/err_pessimistic.php, www/vrat03/cv11/index.php, www/vrat03/cv11/save_optimistic.php, www/vrat03/cv11/save_pessimistic.php
Odevzdávám úkol z 11. cvičení. Odkaz na server eso: [https://eso.vse.cz/~vrat03/cv11/](https://eso.vse.cz/~vrat03/cv11/).
Pozn. pro přihlášení je potřeba zadat ID. Může to být libovolné číslo, které slouží jen k identifikaci uživatele při editaci.
=> vrat03-cv11
